# Site wide configuration

title: "The Azure Stack Forge"
description: "Azure Stack related training material developed and maintained with a little help from my friends"
logo: MSLogo.jpg
teaser: MSLogo.jpg
featured: project.png
locale: en
timezone: Europe/London
url: https://czw2pv.github.io
feed:
  path: atom.xml

# Jekyll configuration

sass:
  sass_dir: _sass
  style: compressed
permalink: pretty
kramdown:
  input: GFM
  toc_levels: 1..2
highlighter: rouge
plugins:
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed

# Front matter defaults
defaults:
  # _posts
  - scope:
      path: "_posts"
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: article
      author_profile: true
      comments: true
      share: true
      related: true
  # images
  - scope:
      path: "images"
    values:
      image: true

# Site owner
owner:
  name: Fredrik Nilsson
  email: fredrik_nilsson@outlook.com
  twitter: https://twitter.com/fredriknilsson_
  bio:
  avatar: gargamel.jpg # 160x160 px image for author byline
  disqus-shortname: https-czw2pv-github-io

include:
  - .htaccess
  - "_pdu"
  - "_workshops"
  - "_posts"
  - "_pages"
  - "_blogs"
  - "_landingpages"
exclude:
  - "*.less"
  - "*.sublime-project"
  - "*.sublime-workspace"
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - CHANGELOG
  - Capfile
  - Gemfile
  - Gruntfile.js
  - LICENSE
  - README
  - Rakefile
  - config
  - github-pages-local.md
  - gulpfile.js
  - lib
  - log
  - node_modules
  - package.json
  - spec
  - tmp
